POST  http://localhost:5500/api/customers/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Duk",
    "lastName": "Maison",
    "email": "Maison@oi.com",
    "password": "fgjy56",
    "gender": "male",
    "birthday": "1936-10-12"
}